### ISSUE TITLE
Suggestions to add Net Ninja, Computerphile, Tom Scott

### ISSUE THREAD

**Issue by vikramnr** [JoseDeFreitas/awesome-youtubers#10]
@JoseDeFreitas  
Below are the link for the channels,
[Net Ninja](https://www.youtube.com/channel/UCW5YeuERMmlnqo4oq8vwUpg)
[Computerphile](https://www.youtube.com/user/Computerphile)
[Tom Scott](https://www.youtube.com/user/enyay)

**Comment by JoseDeFreitas** [comment]
Hello 👋.
I've watched a lot of videos from The Net Ninja. I didn't think about it when adding some channels. Now I added it, as well as Tom Scott. About him, I saw his content is theoretical, so I added that tag. About Computerphile, that channel has been added before. Great channel!
Commit: 851c258.
Thank you for these recommendations!

**Comment by vikramnr** [comment]
Thanks
