### ISSUE TITLE
1#

### ISSUE THREAD

**Issue by 0665611570** [JoseDeFreitas/awesome-youtubers#103]

**Comment by JoseDeFreitas** [comment]
Hello. Did you mean to open this issue? I'm going to keep it opened for some days and close it if there's no response. I recommend you read the [CONTRIBUTING.md file](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/CONTRIBUTING.md) to know more about how to contribute to this repository.

**Comment by JoseDeFreitas** [comment]
Closing this inactive issue.
