### ISSUE TITLE
Add `Franks laboratory` channel

### ISSUE THREAD

**Issue by thisago** [JoseDeFreitas/awesome-youtubers#111]
https://www.youtube.com/@Frankslaboratory

Content about game development, Audio API, Canvas API and Javascript related

**Comment by JoseDeFreitas** [comment]
Hello, @thisago. Sorry for answering more than a week later. I added the channel you suggested, as shown in the commit 65071f363f4f969e4390c8feb5b5d4089c295ef7. Thank you for recommending it!
