### ISSUE TITLE
coaching centre on YouTube 

### ISSUE THREAD

**Issue by ammazanbd** [JoseDeFreitas/awesome-youtubers#122]

**Comment by JoseDeFreitas** [comment]
Hello, @ammazanbd. I can't find any specific "Coaching Centre" YouTube channel. Are you referring to a certain YouTube channel you want to add to the list?

**Comment by JoseDeFreitas** [comment]
As there are no more comments, I'm closing this issue. Feel free to re-opoen it if needed.
