### ISSUE TITLE
Blogging informations

### ISSUE THREAD

**Issue by Wizarden14** [JoseDeFreitas/awesome-youtubers#129]
I need to have blogging informations and need to be better in blogging and this option is not here about blogging, content writing, articles generation etc so kindly include these topics too as soon as possible

**Comment by JoseDeFreitas** [comment]
Hello, @Wizarden14. Sorry for the late response.

For a new section on the list to be created, there needs to be at least one YouTuber in it (this to have a more concise list). No YouTuber that focuses on that topic comes to my mind.

About the suggestion itself, I don't know if "Blogging" would be an useful section: the "Web Development" section seems to cover that content. There are YouTubers that teach how to create a website of any kind, including blog-like ones, and there are even some YouTubers that make tutorials about drag-and-drop website creation platforms.

Content writing and article generation may not fit in this list, which is aimed at more technological topics. I know "Digital Design" and "Audio and Video", which are disciplines by themselves, exist in this list, but they are also complementary for, let's say, a web or game developer.

This is my opinion, but I'd like to hear yours so we can come to an agreement. Thank you for your interest!

**Comment by JoseDeFreitas** [comment]
One month has passed with no response, so I'm closing this issue. Nevertheless, feel free to re-open it if needed. Thank you for the interest in the list.
