### ISSUE TITLE
Web development 

### ISSUE THREAD

**Issue by roshanrathod-46** [JoseDeFreitas/awesome-youtubers#134]

**Comment by JoseDeFreitas** [comment]
Hello, @roshanrathod-46. If you want to request youtubers for the "Web Development" section, you can do so by [contributing](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/CONTRIBUTING.md) or by just telling me what are the channels you believe should be in the list.

**Comment by JoseDeFreitas** [comment]
Since there are no more comments, I'm closing this issue. Feel free to reopen it if needed.
