### ISSUE TITLE
non-English YouTubers and Translation of the guidelines

### ISSUE THREAD

**Issue by JoseDeFreitas** [JoseDeFreitas/awesome-youtubers#14]
I'm creating this issue to write about the [contribution guidelines](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/contributing.md).

I want these [contribution guidelines](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/contributing.md) to be translated into different languages. There're tons of non-English YouTubers, whose some of them are awesome and deserve a place in this list. Because of this, I would want to have lists for every language (listed in the [other-languages folder](https://github.com/JoseDeFreitas/awesome-youtubers/tree/main/other-languages) and then within a folder for every language.) That's why the contribution guidelines being translated is something I find useful.

I'll keep this issue open to discussion so any that is interested in the translation of the guidelines can discuss it and request information or tell other they'll start translating them into their language.

**Comment by JoseDeFreitas** [comment]
Pull request related to this topic: #17 🤝.

**Comment by JoseDeFreitas** [comment]
Pull request related to this topic: #21 🤝.

**Comment by JoseDeFreitas** [comment]
I have changed the title of this issue because the rework of the guidelines has been made (#21.) There may be some edits to the guidelines over time, but they'll stay much as they are.

This issue will keep open for contributions to the [other-languages](https://github.com/JoseDeFreitas/awesome-youtubers/tree/main/other-languages) folder. I'll like to have the [guidelines](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/contributing.md) translated into different languages. Apart from that, this issue will serve to answer possible questions about adding non-English speaker YouTubers.

**Comment by badushaebrahim** [comment]
Hi bro I can make changes to community guidelines and also could translate it to Malayalam, Hindi

**Comment by JoseDeFreitas** [comment]
Hello @badushaebrahim!

I see you're interested in changing something about the [guidelines](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/contributing.md). If you want to, simply make a pull request with your changes so I can review them.

I've created a folder for Malayalam, Hindi: [hindi-malayalam](https://github.com/JoseDeFreitas/awesome-youtubers/tree/main/other-languages/hindi-malayalam). Inside that folder, there's the [contributing-hi_ml.md](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/other-languages/hindi-malayalam/contributing-hi_ml.md) file, which is where the translation should be made. To translate the guidelines take the source from the [english version](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/contributing.md). As you want to change something in the core guidelines, I recommend you do that first and then translating them.

Any queries just message me. Thank you!

**Comment by badushaebrahim** [comment]
hi, i have made the  contribution guidelines in malayalam please verfy and push my commit

**Comment by JoseDeFreitas** [comment]
Hello @badushaebrahim. I don't see any pull request open. Can you checkout and open a pull request with your changes? Or tell me where did you do them. It's preferable that you open a pull request with your changes in this repository so I can review them. Thank you.

**Comment by badushaebrahim** [comment]
https://github.com/badushaebrahim/awesome-youtubers @JoseDeFreitas  this  is the fork with that edits

**Comment by JoseDeFreitas** [comment]
Hello @badushaebrahim. I've opened a pull request and pushed your changes (PR: #56). Thank you a lot for your contribution! 😄
