### ISSUE TITLE
Add a new content

### ISSUE THREAD

**Issue by NEEHITGOYAL** [JoseDeFreitas/awesome-youtubers#42]
I think electronics and IoT is also a really great field to be added these content are really important for an electronics and communication engineering student.

**Comment by JoseDeFreitas** [comment]
Hello @NEEHITGOYAL! Yes, it would be nice to have that section added to the list. I add new sections when there's at least one YouTuber. If I or someone else find an awesome YouTuber specified in that field I'll create the section. Thank you for the recommendation!

**Comment by NEEHITGOYAL** [comment]
@JoseDeFreitas  there is a channel of electronics i watch like  almost daily and it is the channel who teaches electronics deep 
https://www.youtube.com/channel/UCBkOVp1Cqz4MR0LYR8vKpZg
can i add this i mean can i make PR

**Comment by JoseDeFreitas** [comment]
@NEEHITGOYAL for sure! Make a PR so it can be reviewed 👍.
