### ISSUE TITLE
Suggestion to add `Meth Meth Method` and `Ivan talks about computers` channels

### ISSUE THREAD

**Issue by micalevisk** [JoseDeFreitas/awesome-youtubers#45]
Hi! Please take a look at [Meth Meth Method](https://www.youtube.com/c/MethMethMethod) channel. I think this can live under **Web development** or **Programming in general** sections.

Also, [Ivan talks about computers](https://www.youtube.com/channel/UCap3y2TNRqIbTOvnpP-p5Yw) which is small but his videos have good quality and content :)

**Comment by JoseDeFreitas** [comment]
Hello @micalevisk!
About **Meth Meth Method**, I think their tutorials are great. Has a lot of content and explains everything carefully. For sure, a channel that you can learn of. The channel is focused on JavaScript, but most of the tutorials are about Game development. Don't you think the channel should be instead in that category? As the channel is not active at the moment, most of the tutorials you can find are about Game development. If it uploaded not-game dev-related content, it may be in another section.

About **Ivan talks about computers**, it has too few videos with too few minutes long. The tutorials are good, but I consider it should have more awesome content to be on the list, pointing out that looks that it's not active at the moment.

Tell me your thoughts 🤗.

**Comment by micalevisk** [comment]
@JoseDeFreitas I'm with you! **Meth Meth Method** should be in Game development :+1:
