### ISSUE TITLE
Suggestion to add `Redis University` channel

### ISSUE THREAD

**Issue by micalevisk** [JoseDeFreitas/awesome-youtubers#48]
I'm not sure if the channel [Redis University](https://www.youtube.com/c/RedisUniversity) can be fit into "youtubers" world haha but their content about **Redis** is awesome! :smile: But I don't have a clue about it's category.

**Comment by JoseDeFreitas** [comment]
Hello @micalevisk! So sorry for responding to this issue 5 days after it was opened.
Thank you for requesting this channel! I like that the list has now a new awesome channel specialized in technology. The tutorials are concise and explanation. I've added the channel to the "[Programming in general](https://github.com/JoseDeFreitas/awesome-youtubers#programming-in-general)" section.
Commit: ea93960.
If you have any queries, let me know. If not, you can close this issue. Thank you! 🤩
