### ISSUE TITLE
Ben Eater link broken

### ISSUE THREAD

**Issue by HadManySons** [JoseDeFreitas/awesome-youtubers#5]
Correct link to Ben Eater channel is: https://www.youtube.com/c/BenEater

You're missing the r at the end.

**Comment by JoseDeFreitas** [comment]
Hello! Nice catch. I've already fixed it (commit: 6786eca0a8816724cb8efe31c2325bcace7415af). Thank you!

**Comment by HadManySons** [comment]
Awesome
