### ISSUE TITLE
Youtubers 

### ISSUE THREAD

**Issue by josiashod** [JoseDeFreitas/awesome-youtubers#52]

**Comment by JoseDeFreitas** [comment]
Hello @Hod15! Can you please explain to me what this issue is about? Thank you!

**Comment by Hod15** [comment]
Sorry it's a mistake

Le 18 oct. 2020 23:37, "José De Freitas" <notifications@github.com> a
écrit :

**Comment by JoseDeFreitas** [comment]
@Hod15 I see. No problem. I'll close this then. Feel free to contribute or ask something by opening another issue. Thanks ✌.
