### ISSUE TITLE
Suggestion to add `ExplainingComputers` channel

### ISSUE THREAD

**Issue by I3lackRacer** [JoseDeFreitas/awesome-youtubers#54]
[<img align="left" height="94px" width="94px" alt="ExplainingComputers channel's avatar" src="https://yt3.ggpht.com/a/AATXAJy17nmM3at2dVGVn8DmWURJf1eULCoPqC-lS517AQ=s176-c-k-c0x00ffffff-no-rj"/>](https://www.youtube.com/user/explainingcomputers)

[**ExplainingComputers**](https://www.youtube.com/user/explainingcomputers) \
Content about: Raspberry Pi, Electronics, Operation System  \
Featured playlists: `Artificial Intelligence`, `Pi Zero Projects`. `Migrating to Linux`, `Many more` \
<br/>

**Comment by JoseDeFreitas** [comment]
Hello @I3lackRacer! Thank you for requesting this channel.
I've watched some videos and I really liked it. Has awesome hardware tutorials. Very well explained, good and relaxed voice.
I've added it to the "[Hardware](https://github.com/JoseDeFreitas/awesome-youtubers#hardware)" section.
Commit: 21f0f13.
If you have any queries about this, tell me. If not, you can close this issue. Thank you for requesting this! 😁

**Comment by JoseDeFreitas** [comment]
I'll close this issue. If you want, you can re-open it. Thank you a lot for requesting this awesome YouTube channel!
