### ISSUE TITLE
Pygame

### ISSUE THREAD

**Issue by Eclipsu** [JoseDeFreitas/awesome-youtubers#6]
DaFluffyPotato is really good teacher for intermediate python programers teaching basics of pygame. add it or die.

**Comment by JoseDeFreitas** [comment]
I'll review the channel. You can do it by yourself if you want to. If not, I can do it without any problems. Thank you for the recommendation!

**Comment by JoseDeFreitas** [comment]
@Eclipsu hello! I reviewed the channel and watched some videos. They are really great. Thank you for this recommendation! (commit: 1830c64f8566f90c7a5ce9fca0c8d12f0113ed3b).
