### ISSUE TITLE
List item adding request

### ISSUE THREAD

**Issue by aarmn** [JoseDeFreitas/awesome-youtubers#69]
Mohammad archef in list of designers with illustrator would be useful

**Comment by JoseDeFreitas** [comment]
Hello @aarmn! Thank you for adding this YouTube channel.
I've looked through their page and it looks very nice. Great quality videos and tutorials. Their designs are pretty, very well done. YouTuber added to the list!
Commit: 3cd56fc2bcef52c5a908840a488ff4b8b923fede
