### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by kens-visuals** [JoseDeFreitas/awesome-youtubers#76]
Awesome YouTubers linter (https://github.com/kens-visuals/awesome-youtubers/blob/main/linter) link in README.md file is broken

**Comment by JoseDeFreitas** [comment]
Hello @kens-visuals. That URL was linking to a small side-project I made to automatically test the new pull requests, but I removed it because I thought it's unnecessary. Commit associated: dabf87c8a91615e08ed9ba6223e236808c375fbf. Thank you for letting me know!
