### ISSUE TITLE
I have a personal list of channels, Give it a look

### ISSUE THREAD

**Issue by FOSS-Love** [JoseDeFreitas/awesome-youtubers#81]
Why i am not making a PR? as i am bad with categorising. Give them a look and mention me the names of channels you want to add. I will edit markdown and make a PR, as its a bit of a work to do.

Thanks for creating this curated list, its helpful for many.

Give it a look and give me the names.

<https://raindrop.io/alias_raindrop/code-19449714>

<https://raindrop.io/alias_raindrop/design-19453474>

**Comment by JoseDeFreitas** [comment]
Hello @FOSS-Love, thank you for opening this issue. I just took a quick look and wow, there are a lot of channels in there. I have to see each one of them (excluding some that are already in the list) and rate them based on the criteria I follow to add them to the list. Tomorrow I'll take a detailed look and choose the ones I consider the best ones. Feel free to do the same.

**Comment by FOSS-Love** [comment]
The net ninja - Web dev topics well covered, top quality.

Coder coder - makes learning fun, covers small topics, live coding at its best.

Telusko - Some well explained courses, his teaching method feels like some friend is explaining.

kalle hallden - Its fun, well known for his personal projects, and his narration through out the video.

satori graphics - he is soo resourceful, quality content.

Figma - Course to learn figma by its creators, cool right.

design course - provides a lot of tips and provides good content.

zimri mayfield - Logo designs mostly and man he makes it fun to watch,

Check these i find they might fit the list

**Comment by FOSS-Love** [comment]
Let me make it easy for you by removing the channels that are already  made the list.

**Comment by FOSS-Love** [comment]
@JoseDeFreitas I asked one of my friend to categorise my personal list so you can give it a look with ease. i have updated the link with categories, might not be accurate but they are relatable.

<https://raindrop.io/alias_raindrop>

**Comment by JoseDeFreitas** [comment]
Hello again. Sorry for making you wait more than one day, as I previously said “tomorrow”.

I navigated through some tech-related collections (specifically “Code”, “Design”, “Linux”, “Math”, “Privacy” and “Web-Dev”) and pulled out these (in my opinion) awesome channels. If you think there's a good YouTuber from another collection, let me know.

In the `Web development` section:
- [LearnWebCode](https://www.youtube.com/channel/UCHRp19HU7Y2LwfI0Ai6WAGQ)

In the `Computer science` section:
- [Learn Coding](https://www.youtube.com/channel/UCV7cZwHMX_0vk8DSYrS7GCg)
- [Professor Leonard](https://www.youtube.com/channel/UCoHhuummRZaIVX7bD4t2czg)
- [Eddie Woo](https://www.youtube.com/channel/UCq0EGvLTyy-LLT1oUSO_0FQ)

In the `Game development` section:
- [TheDevKing](https://www.youtube.com/channel/UCS2smVWjNGuRzD6HVWmlWwQ)

In the `Cybersecurity` section:
- [Sun Knudsen](https://www.youtube.com/channel/UCkHN7h7CFeYL6Y1N5JcEZug)

In the `Operating systems` section:
- [LearnLinuxTV](https://www.youtube.com/channel/UCxQKHvKbmSzGMvUrVtJYnUA)

In the `Digital design` section:
- [CharliMarieTV](https://www.youtube.com/channel/UCScRSwdX0t31gjk3MYXIuYQ)
- [Yes I'm a Designer](https://www.youtube.com/channel/UCT_of6HCtVZFpnnnLUeAGYA)

I'll wait for your pull request. Thank you again for sending me this list :smile:.
