### ISSUE TITLE
YouTube channels

### ISSUE THREAD

**Issue by ankit-1katewa** [JoseDeFreitas/awesome-youtubers#91]

**Comment by JoseDeFreitas** [comment]
Hello, @ankit-1katewa. Did you mean to open this issue? If you want to request the addition of some YouTube channels, remember that you can create a pull request by yourself; if you don't want to, you can write their names with their links in this issue and I will add them to the list if they match the qualifications. Head to the [CONTRIBUTING.md](https://github.com/JoseDeFreitas/awesome-youtubers/blob/main/CONTRIBUTING.md) file to know more.
