### ISSUE TITLE
Brazilian Portuguese missing

### ISSUE THREAD

**Issue by rcarubbi** [JoseDeFreitas/awesome-youtubers#99]
Could you please add Brazilian Portuguese as an available in the badges file?

**Comment by JoseDeFreitas** [comment]
Hello, @rcarubbi. I only made the badges for languages that are spoken by at least one creator in the list. Thank you for telling me to create one for Portuguese (commit: d2bd9d0fc4e1bb77642ee0e355f022773c0387eb). As you see, I made no distinction between the two accents, just as I didn't for English or Spanish. I hope the list can be expanded with awesome YouTubers that speak Portuguese. I'll keep the issue opened if you or someone else wants to say something. 😄

**Comment by rcarubbi** [comment]
Hi Jose,

Actually, I thought better about it and create a specific list for
Brazilians youbers. With all the categories you created translate to
portuguese. Including the contributions and code of conduct files.

I gave you the credits for the original list and mentioned your list there
as well.

https://github.com/rcarubbi/awesome-brazilian-youtubers


Regards

Em qui., 8 de dez. de 2022 14:16, José de Freitas ***@***.***>
escreveu:

**Comment by JoseDeFreitas** [comment]
Hello again, @rcarubbi.

I just visited the repository you created. Thank you for taking the time to change the list icon and translate every word. I didn't think about creating different repositories for different languages, but I believe it's a good idea, as it's not that easy to search by languages in this list, and the more it grows, the harder it will be to search for YouTubers in the language desired. I may keep this list strictly for English-speaking YouTubers and reference all other repositories from other languages.

Two inquiries: should I merge the pull request #101? That channel is already on your list. Finally, tell me if you want me to put a link to your list in the README file, so people can find your list more easily.

I'm really thankful for all your work :smile:👍.

**Comment by JoseDeFreitas** [comment]
Okay, @rcarubbi. I will now add a link to your repository. And yes, go ahead with the Spanish list. Thank you for doing that work. Some YouTubers that are in this list speak Spanish, so, if you believe they are awesome, you can take them and paste them on your new repository. I may contribute in the future with more Spanish-speaking YouTubers I know.
I'm going to keep this issue open until I made all the changes in my repository.
Have a great day!

**Comment by rcarubbi** [comment]
Hi Jose, I created the spanish list here https://github.com/rcarubbi/awesome-spanish-youtubers
